apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_DB_NAME
  labels:
    app: $APP_DB_NAME
  namespace: $APP_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_DB_NAME
  template:
    metadata:
      labels:
        app: $APP_DB_NAME
    spec:
      serviceAccountName: $APP_SERVICE_ACCOUNT_NAME
      containers:
        - name: $APP_DB_NAME
          image: postgres:9.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: $POSTGRESQL_DB
            - name: POSTGRES_PASSWORD
              value: $POSTGRESQL_PASSWORD
            - name: POSTGRES_USER
              value: $POSTGRESQL_USER
          readinessProbe:
            exec:
              command: [ "psql", "-w", "-U", $POSTGRESQL_USER, "-c", "SELECT 1" ]
            initialDelaySeconds: 20
            timeoutSeconds: 2
---
kind: Service
apiVersion: v1
metadata:
  name: $APP_DB_NAME
spec:
  selector:
    app: $APP_DB_NAME
  ports:
    - port: 5432
      targetPort: 5432