---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-app-sa
  namespace: test-app-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app-secretless
  name: test-app-secretless
  namespace: test-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-secretless
  template:
    metadata:
      labels:
        app: test-app-secretless
    spec:
      serviceAccountName: test-app-sa
      containers:
        - image: docker.io/bnasslahsen/conjur-secretless-k8s-demo
          name: test-app-secretless
          imagePullPolicy: Always
          env:
            - name: DB_URL
              value: jdbc:postgresql://localhost:5432/test_app?sslmode=disable
            - name: DB_USERNAME
              value: dummy
            - name: DB_PASSWORD
              value: dummy
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          ports:
            - containerPort: 8080
        - name: authenticator
          image: docker.io/cyberark/secretless-broker:latest
          imagePullPolicy: Always
          args: ["-f", "/etc/secretless/secretless.yml"]
          ports:
            - containerPort: 5432
          env:
            - name: CONJUR_AUTHN_LOGIN
              value: host/test-app
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: conjur-connect
          volumeMounts:
            - mountPath: /etc/secretless
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: secretless-config
            defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-secretless
  namespace: test-app-namespace
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8086
  selector:
    app: test-app-secretless
