apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $APP_NAME
  name: $APP_NAME
  namespace: $APP_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      serviceAccountName: $SERVICE_ACCOUNT_NAME
      containers:
        - image: $IMAGE_NAME
          name: $APP_NAME
          imagePullPolicy: Always
          env:
            - name: DB_URL
              value: jdbc:postgresql://localhost:5432/$POSTGRESQL_DB?sslmode=disable
            - name: DB_USERNAME
              value: dummy
            - name: DB_PASSWORD
              value: dummy
          ports:
            - containerPort: 8080
        - name: authenticator
          image: docker.io/cyberark/secretless-broker:latest
          imagePullPolicy: Always
          args: ["-f", "/etc/secretless/secretless.yml"]
          ports:
            - containerPort: 5432
          env:
            - name: CONJUR_AUTHN_LOGIN
              value: $HOST_ID
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: conjur-connect
          volumeMounts:
            - mountPath: /etc/secretless
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: secretless-config
            defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
  namespace: $APP_NAMESPACE
spec:
  ports:
    - port: 8080
      targetPort: 8081
  selector:
    app: $APP_NAME
