---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-access
  namespace: $APP_NAMESPACE
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: [ "get", "update" ] # Note only get is required! For demo purpose, to reuse the same Service Account

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: $APP_NAMESPACE
  name: secrets-access-binding
subjects:
  - kind: ServiceAccount
    namespace: $APP_NAMESPACE
    name: $APP_SERVICE_ACCOUNT_NAME
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: secrets-access