---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: conjur-authn-rolebinding
  namespace: $CONJUR_NAMESPACE
subjects:
  - kind: ServiceAccount
    name: $SERVICE_ACCOUNT_NAME
    namespace: $CONJUR_NAMESPACE
roleRef:
  kind: ClusterRole
  name: conjur-clusterrole
  apiGroup: rbac.authorization.k8s.io