spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: user
    password: pass
  jpa:
    generate-ddl: true
    database: h2
    hibernate:
      ddl-auto: update
springdoc:
  writer-with-order-by-keys: true
  swagger-ui:
    use-root-path: true

