---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: conjur-authn-rolebinding
  namespace: cyberark-conjur
subjects:
  - kind: ServiceAccount
    name: authn-k8s-sa
    namespace: cyberark-conjur
roleRef:
  kind: ClusterRole
  name: conjur-clusterrole
  apiGroup: rbac.authorization.k8s.io