version: "2"
services:
  postgres-db:
    connector: pg
    listenOn: tcp://0.0.0.0:5432
    credentials:
      host:
        from: conjur
        get: secrets/test-app/host-postgres
      port:
        from: conjur
        get: secrets/test-app/port-postgres
      username:
        from: conjur
        get: secrets/test-app/username-postgres
      password:
        from: conjur
        get: secrets/test-app/password-postgres
      sslmode: disable